version: 2
updates:
  # GitHub Actions のバージョンを追従
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"

  # lib/libaribb25, lib/recdvb の git submodule を追従
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "submodule"
